config/routes.rb
KissellInfo::Application.routes.draw do

  match '/'         => 'home#index'
  match '/home'     => 'home#index'
  match '/about'    => 'home#about'
  match '/tests'    => 'home#tests'
  match '/contact'  => 'home#contact'
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @title = 'Home'
  end
  
  def about
    @title = 'About'
  end
  
  def tests
    @title = 'Tests'
  end
  
  def contact
    @title = 'Contact'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Account successfully created!"
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>About</h1>
<p>
I have made my life’s goal to apprentice at Hashrocket. I have no formal training, education, or work experience with Ruby or Ruby on Rails. However, I do spend 100% of my free time working to become not only employable, but a master in the field (please don’t mistake passion and aptitude for skill!). I want to make a career out of doing what I love, and cannot fathom a better way to venture towards artisan, than with Hashrocket.  I can absolutely guarantee your time and effort vested in me will benefit you, and the Rails and Open Source community. I promise, let me prove it.

<h2>Pertinent Offerings to an Apprenticeship</h2>


<ul>
  <br>•A love for Ruby and Rails
  <br>•A growing obsession with VIM (I even use Hashrocket’s dotfiles!)
  <br>•A burning desire to excel 
  <br>•A love and need to give back to OSS
</ul>

<p>
A little about myself; I am a 26-year-old Network Support Technician working for a private K-12 in Naples, FL. I live with my wife Katy, and our dog Ruby(seriously). I like to play guitar, read, and hack on ruby. I’ve worked full-time in the Information Technology domain my entire working career. Starting as a Helpdesk Support Technician, where I honed my fanatical customer support skill-set. And then on to working as a Mobile and In-house PC Tech in a fast paced enterprise environment. My current role is applying OS X/*nix domain knowledge to integrate Apple products into a pre-existing Active Directory environment. 
</p>

app/views/home/contact.html.erb
<h2>Contact</h2>
<br>

app/views/home/index.html.erb
<h1>Hi there! My name is Dan.</h1>
<p>I put this site together to demonstrate a simple, web app using Ruby on Rails. Feel free to check out the source on github.</p>

app/views/home/tests.html.erb
<h1>Tests</h1>

<p>These are the RSpec tests I wrote in a Red, Green, (still need to refactor) manner.<p>
<script src="https://gist.github.com/1148445.js"> </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title><%= @title %></title>
<%= stylesheet_link_tag :all %>

</head>
<body>
  <div id="header">
    <%= image_tag("logo.png", :alt => "Wanna be Rockateer", :width => 750, :height => 150)%>
</div>

<div id="navigation">
    <%= link_to "Contact", contact_path %>
    <%= link_to "Tests", tests_path %>
    <%= link_to "About", about_path  %>
    <%= link_to "Home", home_path %>
</div>

<div id="content">

  <%= yield %>


  <center>
<a href="http://twitter.com/_dkissell" class="twitter-follow-button" data-show-count="false">Follow @_dkissell</a>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
</div>

<div id="footer">

</center>
</div>

</body>
</html>

app/views/users/new.html.erb
<h1>Create User Account</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Invalid input.</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :enter_again%><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>